allow_anonymous false

password_file /mosquitto/config/pwfile
acl_file /mosquitto/config/aclfile

# MQTT puerto normal
listener 1883

# MQTT sobre websockets
listener 9001
protocol websockets

# Persistencia
persistence true
persistence_file mosquitto.db
persistence_location /mosquitto/data/

# Evitar bruteforce
max_inflight_bytes 200000
max_connections 50